In [4]:
# test
import numpy as np
f = lambda x : 1 / (1 + np.exp(-x))

In [44]:
a=[1,3,5,7,9]
b = np.array(a)
b[:,None]

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [60]:
a = np.array([[2]])
x[:,None].dot(a)

array([[ 2],
       [ 6],
       [10],
       [14],
       [18]])

In [81]:
x.T

array([[ 0.10562014,  0.39775194, -0.29887597],
       [-0.20185996,  0.50074398,  0.19962801]])

ValueError: shapes (1,1) and (5,) not aligned: 1 (dim 1) != 5 (dim 0)

In [79]:
b = np.array([1])
b

array([1])

In [80]:
x[:,].T

array([[ 0.10562014,  0.39775194, -0.29887597],
       [-0.20185996,  0.50074398,  0.19962801]])

In [21]:
np.dot(b[:,], x) 

ValueError: shapes (1,) and (5,) not aligned: 1 (dim 0) != 5 (dim 0)

In [64]:
y = np.array([[ 0.37275328],[-0.03172939]])
x = np.array([[ 0.10562014, -0.20185996], [0.39775194, 0.50074398], [-0.29887597, 0.19962801]])

In [65]:
y.shape

(2, 1)

In [66]:
x.shape

(3, 2)

In [68]:
xx = x[0]

In [78]:
xx[None,:].shape

(1, 2)

In [82]:
xx

array([ 0.10562014, -0.20185996])

In [86]:
xx[None,:].shape

(1, 2)

In [87]:
xx[None,:]

array([[ 0.10562014, -0.20185996]])

In [91]:
yy = y[1]
yy[:,None].shape

(1, 1)

In [93]:
np.dot(xx[:,None], yy[:,None])

array([[-0.00335126],
       [ 0.00640489]])